# Generated by Django 3.1.3 on 2023-01-30 16:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ingredientes', models.TextField()),
                ('modo_preparacion', models.TextField()),
                ('tiempo_preparacion', models.IntegerField()),
                ('rendimento', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('data_criacao', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('foto', models.ImageField(blank=True, upload_to='recetas/fotos/')),
                ('publicada', models.BooleanField(default=False)),
                ('persona', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogReceta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField()),
                ('accion', models.CharField(max_length=50)),
                ('receta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recetas.receta')),
            ],
        ),
    ]
